### ISSUE TITLE
Does it work in calibre 4?

### ISSUE THREAD

**Issue by kupiqu** [CoffeeQuotes/Calibre-themes-files#1]
Very nice CSS style, however I'm finding trouble trying to reproduce the looks in Calibre 4.12.

This is how it looks like to me:

![image](https://user-images.githubusercontent.com/3875196/78259301-7f872300-74ca-11ea-9683-3d3488536993.png)

Wondering whether you reproduce this issue and found a workaround...

**Comment by kupiqu** [comment]
I fixed background and foreground colors in Calibre settings and applied the correct padding (see #2).

This is the result:

![image](https://user-images.githubusercontent.com/3875196/78272223-3d1a1200-74db-11ea-9d77-fd384d7809e4.png)


I think CSS font is not yet applied though.

**Comment by CoffeeQuotes** [comment]
It looks good now! Thank you!
